
spring:
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  datasource:
    username:
    password:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: cn.xudam.hellospringboot.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    root: info
    cn.xudam: debug
  file:
    max-history: 30
    path: log/blog-dev.log
